[book]
authors = ["zava"]
language = "en"
multilingual = false
src = "src"
title = "AutoPipeline Document"
description = "The document for AutoPipeline."

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/foldright/auto-pipeline"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/foldright/auto-pipeline/edit/main/doc/{path}"
site-url = "/doc/"
