# Quickstart for GitHub Actions
# https://docs.github.com/en/actions/quickstart

name: Strong CI
on:
  push:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
  workflow_dispatch:

jobs:
  test:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: test by multiply java versions

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: setup Java 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: zulu
          # only first java setup need enable cache
          cache: maven
      - name: setup Java 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: microsoft
      - name: setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: microsoft
      - name: setup Java 20
        uses: actions/setup-java@v3
        with:
          java-version: 20
          distribution: zulu
      - name: setup Java 21
        uses: actions/setup-java@v3
        with:
          java-version: 21-ea
          distribution: zulu

      - run: scripts/integration_test
        env:
          JAVA8_HOME: ${{ env.JAVA_HOME_8_X64 }}
          JAVA11_HOME: ${{ env.JAVA_HOME_11_X64 }}
          JAVA17_HOME: ${{ env.JAVA_HOME_17_X64 }}
          JAVA20_HOME: ${{ env.JAVA_HOME_20_X64 }}
          JAVA21_HOME: ${{ env.JAVA_HOME_21_X64 }}

      - name: remove self maven install files
        run: rm -rf $HOME/.m2/repository/com/foldright/auto-pipeline/

      - name: Upload coverage to Codecov
        # https://github.com/marketplace/actions/codecov
        uses: codecov/codecov-action@v3
        with:
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
